# ----ALACRITTY CONFIG----
key_bindings:
  - { key: Return, mods: Shift, chars: "\x1b[13;2u" }
  - { key: Return, mods: Control, chars: "\x1b[13;5u" }

# FONTS
font:
  # Normal (roman) font face
  normal:
    # Font family
    #
    #   - (Linux/BSD) monospace
    #   - (Windows) Consolas
    family: Iosevka Term

    # The `style` can be specified to pick a specific face.
    style: Regular

  # Bold font face
  bold:
    # Font family
    #
    # If the bold family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Iosevka Term

    # The `style` can be specified to pick a specific face.
    style: Semibold

  # Italic font face
  italic:
    # Font family
    #
    # If the italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Iosevka Term

    # The `style` can be specified to pick a specific face.
    style: Oblique

  # Bold italic font face
  bold_italic:
    # Font family
    #
    # If the bold italic family is not specified, it will fall back to the
    # value specified for the normal font.
    family: Iosevka Term

    # The `style` can be specified to pick a specific face.
    style: Semibold Italic

  # Point size
  size: 15

  offset:
    x: 0
    y: 0

# PADDING
# Window padding (changes require restart)
#
# Blank space added around the window in pixels. This padding is scaled
# by DPI and the specified value is always added at both opposing sides.
window:
  padding:
    x: 15
    y: 14

# %%base16_template: alacritty##default %%
# Base16 Dark
# Jonty Doyle
colors:
  # Default colors
  primary:
    background: '0x2E3647'
    foreground: '0xF4F8FF'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0x2E3647'
    cursor: '0xD7E1F5'

  # Normal colors
  normal:
    black:   '0x2E3647'
    red:     '0xFF79C2'
    green:   '0x8FFFBC'
    yellow:  '0xFF92AC'
    blue:    '0x9ADBFF'
    magenta: '0xFDAFFF'
    cyan:    '0x94F2FF'
    white:   '0xD7E1F5'

  # Bright colors
  bright:
    black:   '0x3A4458'
    red:     '0x9CABDF'
    green:   '0x9CA6FF'
    yellow:  '0xE8FFA6'
    blue:    '0xB7E1FF'
    magenta: '0x5E6A83'
    cyan:    '0xA0AECB'
    white:   '0xF4F8FF'

draw_bold_text_with_bright_colors: false

# %%base16_template_end%%

cursor:
  style:
    shape: Beam
  vi_mode_style: Block

