#!/bin/zsh

pkill picom

bspc monitor HDMI1 -d 1 2 3 4 5
bspc monitor eDP1 -d 6 7 8

#bspc desktop 1 -m HDMI1
#bspc desktop 2 -m HDMI1
#bspc desktop 3 -m HDMI1
#bspc desktop 4 -m HDMI1
#bspc desktop 5 -m HDMI1

bspc config top_padding 25
$HOME/.config/polybar/polydocked.sh

picom &

notify-send "Docked"
