#!/bin/sh
OFFSET=5
file=$1
w=$(($2-$OFFSET))
h=$3

case "$file" in
    *.tar*) tar tf "$1";;
    *.zip) unzip -l "$1";;
    *.rar) unrar l "$1";;
    *.7z) 7z l "$1";;
    *.pdf) pdftotext -f 1 -l 2 "$1" -;;
    *.jpg|*.JPG|*.jpeg|*.png|*.PNG) chafa -f symbols -s "${w}x${h}" "$1";;
    *) bat --color=always --theme=base16 --style="plain" "$1";;
esac
