#! /bin/sh
# Init Programs
killall -q redshift 
sxhkd &
redshift -l -55.33:25.23 -t 6500:5200 &
syncthing --no-browser &
mount_vula.py &
autorandr -c
dunst &

# Wallpaper & Colour Scheme
feh --bg-scale /home/jonty/.cache/wallpaper/current.jpg

# Linking external rules
#bspc config external_rules_command "/home/jonty/.config/bspwm/bspwmrules"

# QOL Settings
xbacklight -set 90
amixer set Master 40%

# Monitors & Screens
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8

# Not used
bspc config focused_border_color  '#FFFFFF'
bspc config normal_border_color   '#FFFFFF'
bspc config border_width          0

bspc config window_gap            14
bspc config remove_unplugged_monitors true

bspc config split_ratio           0.52

bspc config focus_follows_pointer true
bspc config swallow_first_click   false

bspc rule -a Zathura state=tiled
bspc rule -a "R_x11" state=floating rectangle=800x600+560+240
