set positional-arguments

# Install dependencies (root + extensions/lsp)
install:
    npm install
    cd ./extensions/lsp && npm install

# Remove all node_modules
clean:
    rm -rf node_modules extensions/*/node_modules

# Type-check all TS
check:
    npm run check

# Full clean + reinstall
rebuild: clean install
