[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.iosevka-custom.variants]
  inherits = "ss20"

    [buildPlans.iosevka-custom.variants.design]
    asterisk = "penta-low"
    ampersand = "upper-open"
    percent = "rings-continuous-slash"
    lig-neq = "slightly-slanted"
    lig-equal-chain = "without-notch"
    lig-hyphen-chain = "without-notch"
    lig-double-arrow-bar = "without-notch"
    lig-single-arrow-bar = "without-notch"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.semibold]
shape = 600
menu = 600
css = 600

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700
