#!/bin/zsh

dirs=(
  "xresources/.Xresources"
  "alacritty/alacritty.yml"
  "polybar/config" 
  "rofi/rofi.rasi" 
  "nvim/lua/colors/colors.lua"
  "zsh/fzfcolors.zsh"
  "zathura/zathurarc"
  "dunst/dunstrc"
  "sc-im/theme"
)

for i in ${dirs[*]}; do
  pybase16 inject -s $1 -f "/home/jonty/other/dotfiles/config/"$i
done

notify-send "Colorscheme: $1"
