#!/bin/zsh

# Move to base repo
set -e
cd ~/other/dotfiles || exit

# Push & update each submodule
git submodule foreach git push || exit
git submodule update --recursive --remote

# Add all submodules
git add colors config/dwm config/nvim
git commit -m "submodule version update" || exit

# Push to github
git push
notify-send "Pushed Dotfiles"
