#!/bin/sh
set -e
IMAGEDIR="$XDG_CACHE_HOME/wallpaper/"
TEMPNAME="current"

TEMPFILE="$IMAGEDIR/$TEMPNAME.jpg"

if [ ! -f  "$TEMPFILE" ]; then
  mkdir "$IMAGEDIR"
  touch "$TEMPFILE"
fi

cp "$1" "$TEMPFILE" || exit
feh --no-fehbg --bg-scale "$TEMPFILE"

dunstify "Wallpaper Updated"
