#!/bin/zsh

DOTFOLDER="$HOME/other/dotfiles"
CFGFOLDERS=('config' 'scripts')
HOMEFILES=('.xinitrc' '.zprofile')

echo "Symlinking Config..."

mkdir -p ~/.scripts/
cd $DOTFOLDER || exit

# All stowable folders
for i in "${CFGFOLDERS[@]}"; do
  /opt/homebrew/bin/stow -t $HOME/.$i/ $i || exit
done

# The rest
for i in "${HOMEFILES[@]}"; do
  ln -sf $DOTFOLDER/$i $HOME || exit
done

# Re-Source zprofile
source ~/.zprofile || exit

echo "Success!"
