#!/usr/bin/python
import sys
import subprocess

sites = { 
    'cs':'https://vula.uct.ac.za/dav/2ba86917-5774-4a9f-8966-3953651a27c9',
    'ia':'https://vula.uct.ac.za/dav/db2e1ed3-b01c-41a8-9fcd-d295db2640db',
    'inf':'https://vula.uct.ac.za/dav/40ba62d6-1cfb-4b69-9fc2-880384d76854',
}

if (sys.argv[1]):
    arg = sys.argv[1]
else:
    sys.exit(1)

for dir, site in sites.items():
    process = subprocess.run(['sudo', arg, '-t', 'davfs', site, '/home/jonty/university/'+dir+'/vula'])
    if process.returncode == 0: print('Mounted ' + dir + '.')

# Update "/etc/davfs2/secrets" for auto-authentication
