# Paths
alacritty: "alacritty/alacritty.yml"
kitty: "kitty/colors.conf"
neovim: "nvim/lua/highlight.lua"
dunst: "dunst/dunstrc"
polybar: "polybar/config"
rofi: "rofi/themes/rofi.rasi"
fzf: "zsh/fzfcolors.zsh"
